### ISSUE TITLE
What version CentOS

### ISSUE THREAD

**Issue by jervolino** [flakshack/SysAdminBoard#5]
Just curious as to what version of CentOS you setup the server pieces on, running into an issue where none of the python things will pull data from the devices i am trying to query.  And I think it might be CentOS

**Comment by MixWizard** [comment]
Both my test and production instances are running on CentOS 6.6. I haven’t put the config on the new instance yet though. I will let you know if this is still successfully able to pull stats.

 

Regards,

 

Gareth Langham

 

Mob: +44 (0)7912 176 123

Skype: Gareth.Langham

 <http://garethlangham.co.uk/> http://garethlangham.co.uk 

 <https://twitter.com/intent/follow?original_referer=https%3A%2F%2Ftwitter.com%2Fabout%2Fresources%2Fbuttons&region=follow_link&screen_name=M1xWizard&tw_p=followbutton&variant=2.0>   <http://uk.linkedin.com/in/garethlangham/>

**Comment by jervolino** [comment]
i386 or x96_64?

**Comment by jervolino** [comment]
sorry x86_64

**Comment by MixWizard** [comment]
X86_64

 

I have put in some of the hosts and it looks to be connecting and pulling data correctly.

 

Regards,

 

Gareth
